[build]
command = "yarn build"
publish = "build"
# redeploy if either base directory site/ or assets/ changed
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../assets"

[build.environment]
NODE_VERSION = "17.6.0"
YARN_VERSION = "1.22.17"

# proxy plausible script to avoid being falsely blocked
# https://plausible.io/docs/proxy/guides/netlify
[[redirects]]
from = "/js/script.js"
to = "https://plausible.io/js/plausible.js"
status = 200

[[redirects]]
from = "/api/event"
to = "https://plausible.io/api/event"
status = 202
